### ISSUE TITLE
Compile Err

### ISSUE THREAD

**Issue by tomekb530** [danielga/sourcesdk-minimal#10]
```make[1]: *** No rule to make target '../../../../sourcesdk-minimal/tier1/appinstance.cpp', needed by '../../../../gm_luaerror/projects/linux/gmake/x64/release/intermediate/tier1/appinstance.o'.  Stop.``` i cant compile for 64 cause of this i use garrysmod_common x64branch

**Comment by danielga** [comment]
The x64 branch isn't complete.

**Comment by test-mod** [comment]
It has been some time, is the x64 branch open for testing?
