### ISSUE TITLE
x64 Branch Status

### ISSUE THREAD

**Issue by test-mod** [danielga/sourcesdk-minimal#12]
It has been some time since you have last replied about x64 branch

Is it still being worked on?

**Comment by danielga** [comment]
Short answer: no.

Long answer: too much work will be required to have something decent working. All symbols are being stripped on Garry's Mod (wow, took them long enough to realize they could do that), some code from newer Source engine branches was merged and all my efforts until now were basically copying files from CS: GO. The legality of this is questionable, even though only the files that already existed on the SDK were updated. So, unless something changes in the future, this is pretty much doomed.
