### ISSUE TITLE
Compile issue using make on wsl linux(log file included)

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/sourcesdk-minimal#14]
[make.txt](https://github.com/danielga/sourcesdk-minimal/files/4349060/make.txt)
Currently I've gotten wsl setup as travis was being quite a pain. I've already setup the env variables using:
export GARRYSMOD_COMMON=/mnt/c/my_Modules_linux/garrysmod_common/
export SOURCE_SDK=/mnt/c/my_Modules_linux/sourcesdk-minimal/

When trying to compile a modified version of gmsv_serversecure I recieved some issues, so I attempted to compile an unedited copy of the module and got the same exact errors popping up. the sourcesdk_minimal installed is from the default branch of the repo(same goes gor garrysmod_common aswell) the 2 folders in the directory for gm common and sourcesdk are exactly as they are on the root of both repos.

log file included from the compile using `make 2>&1 | tee make.txt`

**Comment by danielga** [comment]
You're compiling the x86_64 version of the module, that's not supported yet on sourcesdk-minimal. Add the flag `config=releasewithsymbols_x86` to compile the `Release With Symbols x86` version.
