### ISSUE TITLE
Question about calling into non-pure virtual function

### ISSUE THREAD

**Issue by Cheatoid** [danielga/sourcesdk-minimal#22]
> Suppose I want to call the non-pure virtual function... Let's just pick this one for instance (just a random good candidate):
https://github.com/danielga/sourcesdk-minimal/blob/989802584aa3f371710d68623553c004dbd24cdc/game/client/c_baseplayer.h#L637

> It also has no implementation in SDK; What am I to do? How to call such a function (assuming I have player object I wish to call it on)?

(P.S. I was asked to give you ^ question, a friend says he is having linking errors when trying to call such method.)

----

Also just one more separate thing I wanted to point out, why not bring GMod-related classes such as `CLuaGameSystem`, ~~`GModDataPack`~~, `CGMODRules`/`C_GMODRules`, `CGMOD_Player`/`C_GMOD_Player`, etc?

**Comment by danielga** [comment]
You can't link with those functions. You'll need to get their address and transform it into a callable pointer.
About the missing classes/interfaces, it's a waste of time for me, don't need them.
