### ISSUE TITLE
appframework/iappsystem.h not such file or directory

### ISSUE THREAD

**Issue by Equoo** [danielga/sourcesdk-minimal#35]
theses two headers use `#include "appframework/iappsystem.h"`
but others uses `#include "appframework/IAppSystem.h"`

https://github.com/danielga/sourcesdk-minimal/blob/1cacb57cd36ee5b77c970e91fff374046aa8574d/public/soundsystem/isoundsystem.h#L13

https://github.com/danielga/sourcesdk-minimal/blob/1cacb57cd36ee5b77c970e91fff374046aa8574d/public/materialsystem/imaterialsystem.h#L26

**Comment by danielga** [comment]
Fixed on both branches (each with their own appropriate capitalisation).
