### ISSUE TITLE
Can't compile mathlib on x86_64

### ISSUE THREAD

**Issue by meetric1** [danielga/sourcesdk-minimal#46]
Something was changed on this line recently for some reason. Reverting to the `x86_64-backup` branch (before the change) fixes the issue. I think we just need to specify that `c` is an `int` 
https://github.com/danielga/sourcesdk-minimal/blob/8627f3c6ab7faa7263a97c4618a590c3185f812d/mathlib/imagequant.cpp#L69

![image](https://github.com/user-attachments/assets/31f8d0b3-32f3-4afe-be62-e4d04ea630a9)

**Comment by danielga** [comment]
Yep, the definitions `int x,y,c;` outside of the loops were commented, and this specific loop was forgotten.

**Comment by danielga** [comment]
It should be fixed now. Force-pushed to garrysmod_common x86-64 branch.
